// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZdJ8HrCOgX7GcM7fRrGra-u87CaBKroc',
    appId: '1:584592116097:android:be532c8a5f0b196a64c080',
    messagingSenderId: '584592116097',
    projectId: 'comidas-tipicas-belem',
    databaseURL: 'https://comidas-tipicas-belem-default-rtdb.firebaseio.com',
    storageBucket: 'comidas-tipicas-belem.appspot.com',
  );
}
